---
version: '3.3'
services:

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      back_net:
        aliases:
          - zipkin
      front_net:
        aliases:
          - zipkin

  fluentd:
    image: ${USERNAME}/fluentd:1.9
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      back_net:
        aliases:
          - fluentd

  elasticsearch:
    image: elasticsearch:7.10.1
    environment: 
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      back_net:
        aliases:
          - elasticsearch

  kibana:
    image: kibana:7.10.1
    ports:
      - "5601:5601"
    networks:
      back_net:
        aliases:
          - kibana

networks:
  back_net:
  front_net:
...