version: '3.3'
services:
  post_db:
    image: mongo:latest
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:logging
    ports:
      - 9292:9292/tcp
    networks:
      front_net:
        aliases:
          - ui
  post:
    image: ${USERNAME}/post:logging
    networks:
      back_net:
        aliases:
          - post
      front_net:
        aliases:
          - post
  comment:
    image: ${USERNAME}/comment:logging
    networks:
      back_net:
        aliases:
          - prom
      front_net:
        aliases:
          - prom

volumes:
  post_db:

networks:
  front_net:
  back_net:
